name = "worker-testing-example"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-20"
compatibility_flags = ["nodejs_compat"]


[build]
command = "cargo install -q worker-build && worker-build --release"
